#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import zipfile

ROOT = Path(__file__).resolve().parents[1]
BUNDLE_DIR = ROOT / "src" / "art" / "_vllm_runtime"
BUNDLE_MARKER = BUNDLE_DIR / ".art_generated"
PROTOCOL_VERSION = 1


def run(command: list[str], *, cwd: Path = ROOT) -> None:
    print("+", " ".join(command), flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def read_pyproject(path: Path) -> dict:
    return tomllib.loads(path.read_text())


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def clean_bundle_dir() -> None:
    if not BUNDLE_DIR.exists():
        return
    if not BUNDLE_MARKER.exists():
        raise RuntimeError(
            f"Refusing to remove non-generated runtime bundle directory: {BUNDLE_DIR}"
        )
    shutil.rmtree(BUNDLE_DIR)


def build_runtime_wheel(runtime_dist: Path) -> Path:
    run(["uv", "lock", "--project", "vllm_runtime", "--check"])
    run(
        [
            "uv",
            "build",
            "--wheel",
            "vllm_runtime",
            "--out-dir",
            str(runtime_dist),
            "--no-progress",
        ]
    )
    wheels = sorted(runtime_dist.glob("art_vllm_runtime-*.whl"))
    if len(wheels) != 1:
        raise RuntimeError(f"Expected one art-vllm-runtime wheel, found {wheels}")
    return wheels[0]


def write_bundle(runtime_wheel: Path) -> None:
    root_project = read_pyproject(ROOT / "pyproject.toml")["project"]
    runtime_project = read_pyproject(ROOT / "vllm_runtime" / "pyproject.toml")[
        "project"
    ]
    pyproject = ROOT / "vllm_runtime" / "pyproject.toml"
    lockfile = ROOT / "vllm_runtime" / "uv.lock"

    BUNDLE_DIR.mkdir(parents=True)
    shutil.copy2(pyproject, BUNDLE_DIR / "pyproject.toml")
    shutil.copy2(lockfile, BUNDLE_DIR / "uv.lock")
    shutil.copy2(runtime_wheel, BUNDLE_DIR / runtime_wheel.name)

    manifest = {
        "art_package": root_project["name"],
        "art_version": root_project["version"],
        "runtime_package": runtime_project["name"],
        "runtime_version": runtime_project["version"],
        "protocol_version": PROTOCOL_VERSION,
        "python": runtime_project["requires-python"],
        "runtime_wheel": runtime_wheel.name,
        "runtime_wheel_sha256": sha256_file(runtime_wheel),
        "pyproject": "pyproject.toml",
        "pyproject_sha256": sha256_file(pyproject),
        "lockfile": "uv.lock",
        "lockfile_sha256": sha256_file(lockfile),
    }
    (BUNDLE_DIR / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    BUNDLE_MARKER.write_text("generated by scripts/build_package.py\n")


def build_root_package(*, wheel_only: bool, out_dir: Path) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    command = ["uv", "build", "--out-dir", str(out_dir), "--no-progress"]
    if wheel_only:
        command.append("--wheel")
    run(command)


def wheel_metadata(wheel: Path) -> str:
    with zipfile.ZipFile(wheel) as archive:
        metadata_names = [
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA")
        ]
        if len(metadata_names) != 1:
            raise RuntimeError(f"Expected one METADATA file in {wheel}")
        return archive.read(metadata_names[0]).decode()


def verify_wheel(wheel: Path) -> None:
    expected = {
        "art/_vllm_runtime/manifest.json",
        "art/_vllm_runtime/pyproject.toml",
        "art/_vllm_runtime/uv.lock",
        "art/megatron/_hybrid_ep/LICENSE",
        "art/megatron/_hybrid_ep/setup.py",
        "art/megatron/_hybrid_ep/csrc/hybrid_ep/backend/hybrid_ep_backend.cuh",
        "art/megatron/_hybrid_ep/deep_ep/hybrid_ep_buffer.py",
    }
    with zipfile.ZipFile(wheel) as archive:
        names = set(archive.namelist())
        missing = expected - names
        runtime_wheels = [
            name
            for name in names
            if name.startswith("art/_vllm_runtime/art_vllm_runtime-")
            and name.endswith(".whl")
        ]
    if missing:
        raise RuntimeError(f"Wheel missing runtime bundle files: {sorted(missing)}")
    if len(runtime_wheels) != 1:
        raise RuntimeError(
            f"Expected one bundled runtime wheel, found {runtime_wheels}"
        )

    bad_dependencies: list[str] = []
    for line in wheel_metadata(wheel).splitlines():
        if not line.startswith("Requires-Dist:"):
            continue
        requirement = line.removeprefix("Requires-Dist:").strip().lower()
        if requirement.startswith("vllm") or requirement.startswith("art-vllm-runtime"):
            bad_dependencies.append(line)
    if bad_dependencies:
        raise RuntimeError(
            "Root wheel must not depend on vLLM runtime packages: "
            + "; ".join(bad_dependencies)
        )


def verify_sdist(sdist: Path) -> None:
    expected = {
        "src/art/_vllm_runtime/manifest.json",
        "src/art/_vllm_runtime/pyproject.toml",
        "src/art/_vllm_runtime/uv.lock",
        "src/art/megatron/_hybrid_ep/LICENSE",
        "src/art/megatron/_hybrid_ep/setup.py",
        "src/art/megatron/_hybrid_ep/csrc/hybrid_ep/backend/hybrid_ep_backend.cuh",
        "src/art/megatron/_hybrid_ep/deep_ep/hybrid_ep_buffer.py",
    }
    with tarfile.open(sdist) as archive:
        names = set(archive.getnames())
    prefix = next(iter(names)).split("/", 1)[0]
    missing = {f"{prefix}/{name}" for name in expected} - names
    runtime_wheels = [
        name
        for name in names
        if name.startswith(f"{prefix}/src/art/_vllm_runtime/art_vllm_runtime-")
        and name.endswith(".whl")
    ]
    if missing:
        raise RuntimeError(f"sdist missing runtime bundle files: {sorted(missing)}")
    if len(runtime_wheels) != 1:
        raise RuntimeError(
            f"Expected one bundled runtime wheel, found {runtime_wheels}"
        )


def verify_dist(out_dir: Path, *, wheel_only: bool) -> None:
    root_wheels = sorted(out_dir.glob("openpipe_art-*.whl"))
    if len(root_wheels) != 1:
        raise RuntimeError(f"Expected one openpipe-art wheel, found {root_wheels}")
    verify_wheel(root_wheels[0])

    if wheel_only:
        return
    sdists = sorted(out_dir.glob("openpipe_art-*.tar.gz"))
    if len(sdists) != 1:
        raise RuntimeError(f"Expected one openpipe-art sdist, found {sdists}")
    verify_sdist(sdists[0])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build ART package artifacts")
    parser.add_argument("--wheel", action="store_true", help="Build only the wheel")
    parser.add_argument("--out-dir", default="dist", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out_dir = args.out_dir
    if not out_dir.is_absolute():
        out_dir = ROOT / out_dir

    clean_bundle_dir()
    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            runtime_wheel = build_runtime_wheel(Path(temp_dir))
            write_bundle(runtime_wheel)
            build_root_package(wheel_only=args.wheel, out_dir=out_dir)
            verify_dist(out_dir, wheel_only=args.wheel)
    finally:
        clean_bundle_dir()
    return 0


if __name__ == "__main__":
    sys.exit(main())
